import { createHmac, randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';

export const SESSION_COOKIE = 'dk_admin';
/** Long enough that the owner is not re-typing the password mid-edit. */
const SESSION_MS = 12 * 60 * 60 * 1000;

const SCRYPT_KEYLEN = 64;

const equal = (a: string, b: string) => {
  const x = Buffer.from(a, 'utf8');
  const y = Buffer.from(b, 'utf8');
  // timingSafeEqual throws on a length mismatch, which would itself leak length.
  return x.length === y.length && timingSafeEqual(x, y);
};

/** `salt:hash`, both hex. Generated by `npm run admin:password`. */
export function hashPassword(password: string, salt = randomBytes(16).toString('hex')) {
  return `${salt}:${scryptSync(password, salt, SCRYPT_KEYLEN).toString('hex')}`;
}

export function verifyPassword(password: string): boolean {
  const stored = process.env.ADMIN_PASSWORD_HASH;
  if (!stored) return false;

  const [salt, hash] = stored.split(':');
  if (!salt || !hash) return false;

  let candidate: Buffer;
  try {
    candidate = scryptSync(password, salt, SCRYPT_KEYLEN);
  } catch {
    return false;
  }
  const expected = Buffer.from(hash, 'hex');
  return candidate.length === expected.length && timingSafeEqual(candidate, expected);
}

const sign = (payload: string) => {
  const secret = process.env.ADMIN_SESSION_SECRET;
  if (!secret) throw new Error('ADMIN_SESSION_SECRET is not set');
  return createHmac('sha256', secret).update(payload).digest('base64url');
};

/** The token carries nothing but its own expiry — there is exactly one account. */
export function createSessionToken(now = Date.now()): string {
  const expires = String(now + SESSION_MS);
  return `${expires}.${sign(expires)}`;
}

export function verifySessionToken(token: string | undefined, now = Date.now()): boolean {
  if (!token) return false;

  const dot = token.indexOf('.');
  if (dot < 1) return false;

  const expires = token.slice(0, dot);
  const signature = token.slice(dot + 1);
  if (!/^\d+$/.test(expires)) return false;

  let expected: string;
  try {
    expected = sign(expires);
  } catch {
    return false;
  }
  // Check the signature before trusting the expiry it protects.
  return equal(signature, expected) && Number(expires) > now;
}

export const sessionMaxAgeSeconds = SESSION_MS / 1000;
